USE Elidek;

insert into Deliverable (title, summary, delivery_date, project_id) values ('Diverse analyzing hub', 'Down-sized holistic analyzer', '2020-11-20', 1);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Reactive uniform matrices', 'Exclusive holistic definition', '2015-08-08', 2);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Synergistic empowering synergy', 'Progressive actuating knowledge user', '2017-01-01', 3);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Re-contextualized regional open architecture', 'Streamlined homogeneous knowledge base', '2016-03-23', 4);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Open-architected well-modulated challenge', 'Integrated global knowledge base', '2021-01-01', 5);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Diverse intangible circuit', 'Cross-group actuating architecture', '2021-04-10', 6);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Distributed 24 hour help-desk', 'Ergonomic reciprocal firmware', '2023-04-01', 7);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Reduced contextually-based moratorium', 'Grass-roots actuating open architecture', '2020-07-03', 8);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Pre-emptive didactic functionalities', 'Balanced well-modulated open architecture', '2018-09-11', 9);
insert into Deliverable (title, summary, delivery_date, project_id) values ('De-engineered exuding frame', 'Open-source didactic attitude', '2019-05-03', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Synchronised static budgetary management', 'Ergonomic intangible neural-net', '2020-10-17', 11);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Open-architected zero administration moderator', 'Cross-platform 24/7 adapter', '2019-07-20', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Fully-configurable asymmetric artificial intelligence', 'Seamless dynamic application', '2023-10-05', 13);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cloned optimal model', 'Face to face clear-thinking archive', '2023-07-22', 14);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Fully-configurable 24 hour middleware', 'Cross-platform hybrid application', '2018-04-17', 15);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Customer-focused demand-driven help-desk', 'Enhanced next generation neural-net', '2021-10-10', 16);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Customer-focused leading edge functionalities', 'Object-based well-modulated software', '2022-01-18', 17);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Focused static groupware', 'Future-proofed national capacity', '2023-05-07', 18);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Multi-channelled intermediate function', 'Multi-channelled stable policy', '2023-10-28', 19);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Profound 3rd generation projection', 'De-engineered value-added success', '2019-02-25', 20);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cross-group content-based success', 'Reverse-engineered discrete concept', '2018-01-05', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Distributed zero administration budgetary management', 'Distributed multimedia portal', '2018-05-25', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Reactive coherent software', 'Self-enabling upward-trending throughput', '2019-03-25', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Cross-platform eco-centric task-force', 'Progressive modular contingency', '2019-05-20', 10);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Polarised mobile array', 'Multi-tiered stable conglomeration', '2018-07-20', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Profit-focused transitional service-desk', 'Sharable radical hierarchy', '2019-01-05', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Multi-tiered well-modulated installation', 'Focused responsive help-desk', '2019-05-05', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Reactive content-based ability', 'Balanced transitional system engine', '2020-01-03', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('User-centric neutral moratorium', 'Innovative methodical conglomeration', '2021-01-08', 12);
insert into Deliverable (title, summary, delivery_date, project_id) values ('Multi-lateral context-sensitive website', 'Stand-alone multi-tasking algorithm', '2024-01-01', 13);
