USE Elidek;

insert into Relates (scientific_field_name, project_id) values ('Mathematics', 91);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 61);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 48);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 99);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 59);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 41);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 95);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 53);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 61);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 83);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 70);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 90);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 81);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 62);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 45);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 72);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 68);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 49);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 1);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 23);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 10);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 57);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 76);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 69);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 24);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 27);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 93);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 98);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 4);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 71);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 100);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 66);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 17);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 13);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 98);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 50);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 57);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 34);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 4);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 46);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 38);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 34);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 82);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 23);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 80);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 26);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 33);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 66);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 96);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 10);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 14);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 93);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 45);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 76);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 7);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 56);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 56);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 95);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 54);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 72);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 58);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 13);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 39);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 5);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 29);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 57);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 13);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 35);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 8);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 39);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 94);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 53);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 35);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 82);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 91);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 2);
insert into Relates (scientific_field_name, project_id) values ('Agricultural Sciences', 33);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 100);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 36);
insert into Relates (scientific_field_name, project_id) values ('Humanity Sciences and Art', 47);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 35);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 74);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 44);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 31);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 83);
insert into Relates (scientific_field_name, project_id) values ('Business and Management Administration', 61);
insert into Relates (scientific_field_name, project_id) values ('Life Sciences', 63);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 44);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 29);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 76);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 61);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 28);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 74);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 17);
insert into Relates (scientific_field_name, project_id) values ('Engineering and Technology', 87);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 90);
insert into Relates (scientific_field_name, project_id) values ('Social Sciences', 51);
insert into Relates (scientific_field_name, project_id) values ('Natural Sciences', 66);
insert into Relates (scientific_field_name, project_id) values ('Mathematics', 64);
insert into Relates (scientific_field_name, project_id) values ('Environment and Energy', 14);
